name: WebApp Deploy

on:
  push:
    branches: [develop, main]
    paths:
      - "2-tf-aws-webapp-ha/**"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2-tf-aws-webapp-ha
    environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: >
          terraform plan
          -var-file="envs/${{ github.ref_name == 'main' && 'prod' || 'dev' }}/terraform.tfvars"
          -out=plan.tfplan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve plan.tfplan
